### ISSUE TITLE
BUG: RaggedArray init may need to be stricter?

### ISSUE THREAD

**Issue by tylerjereddy** [bionumpy/npstructures#15]
`npstructures` `0.2.16`  on Python 3.12 x86_64 Linux

The second print below fails. I'm not sure what the intended behavior is, but I suspect I shouldn't even be able to get as far as that print, and instead get a failure on initialization?

```python
from npstructures import RaggedArray

# this works
x = RaggedArray([[0, 1, 2, 3], [4, 5, 6]])
print(x)

# this fails
x = RaggedArray([0, 1, 2, 3], [4, 5, 6])
print(x)
```

Error:

```
[0 1 2 3]
[4 5 6]
Traceback (most recent call last):
  File "/home/treddy/rough_work/test.py", line 9, in <module>
    print(x)
  File "/home/treddy/python_venvs/py_312_bionumpy_review/lib/python3.12/site-packages/npstructures/raggedarray/__init__.py", line 162, in __str__
    return "\n".join(str(row) for row in self[:20])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/treddy/python_venvs/py_312_bionumpy_review/lib/python3.12/site-packages/npstructures/raggedarray/__init__.py", line 141, in __iter__
    flat = self.ravel()
           ^^^^^^^^^^^^
  File "/home/treddy/python_venvs/py_312_bionumpy_review/lib/python3.12/site-packages/npstructures/raggedarray/base.py", line 78, in ravel
    self._flatten_myself()
  File "/home/treddy/python_venvs/py_312_bionumpy_review/lib/python3.12/site-packages/npstructures/raggedarray/base.py", line 62, in _flatten_myself
    self.__data = self.__data[idx]
                  ~~~~~~~~~~~^^^^^
IndexError: index 4 is out of bounds for axis 0 with size 4
```

**Comment by knutdrand** [comment]
Thanks, the __init__ of RaggedArray is overloaded in a bit unfortunate way, where two arguments are interpreted as (continous_array, shape) where continous_array is a 1d array and shape specifies the row_lenghts. Added a check now that asserts that the provided shape matches up with the given data to avoid confusion
